
# vim: tabstop=4

BUILD_DIR?=$(PWD)/build

PKGCONF=$(shell which pkg-config || which pkgconf)

ifndef PKGCONF
	$(error Can't find pkg-config or pkgconf)
endif

INCLUDE_DIR=$(PWD)/include

CXX_STD=c++17
CC_STD=c11

EXT_DEPS=sdl2 glew

CXXFLAGS=-std=$(CXX_STD) -I$(INCLUDE_DIR) $(shell $(PKGCONF) --cflags-only-I $(EXT_DEPS))
CCFLAGS=-std=$(CC_STD) -I$(INCLUDE_DIR) $(shell $(PKGCONF) --cflags-only-I $(EXT_DEPS))
LDFLAGS=$(shell $(PKGCONF) --libs $(EXT_DEPS))

ifdef NDEBUG
	CXXFLAGS+= -DNDEBUG
	CCFLAGS+= -DNDEBUG
endif

all: little_game

little_game: $(BUILD_DIR)/little_game

$(BUILD_DIR)/little_game: $(BUILD_DIR)/obj/main.cpp.o $(BUILD_DIR)/obj/glDebug.c.o
	@mkdir -p $(dir $@)
	@echo \$$\(CXX\) $^
	@$(CXX) -o $@ $^ $(LDFLAGS)

$(BUILD_DIR)/obj/%.cpp.o: $(PWD)/src/%.cpp
	@mkdir -p $(dir $@)
	@echo "\$$(CXX) -c $^"
	@$(CXX) $(CXXFLAGS) -c -o $@ $^

$(BUILD_DIR)/obj/%.c.o: $(PWD)/src/%.c
	@mkdir -p $(dir $@)
	@echo "\$$(CC)  -c $^"
	@$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -r $(BUILD_DIR)
