name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Building for x86_64-pc-linux-gnu (${{ matrix.build_type }}) with ${{ matrix.compiler.c }}
    container:
      image: docker.io/stellasmith/vgame_builder:1
      volumes:
        - ~/.conan/data:/root/.conan/data
        - ~/.cache/ccache:/root/.cache/ccache
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc
            cxx: g++
          - c: clang
            cxx: clang++
        build_type:
          - Release
          - Debug

    steps:
    - uses: actions/checkout@v2

    - name: cache conan packages
      uses: actions/cache@v2
      with:
        path: ~/.conan/data
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:conan

    - name: cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.cache/ccache
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:ccache

    - name: Configure & Build Tools
      run: |
        set -e
        cmake -S tools/ -B build/tools-build/ -DCMAKE_BUILD_TYPE=Release
        cmake --build build/tools-build/ --parallel
        exec cmake --install build/tools-build/ --prefix build/tools-install/

    - name: Configure
      env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        export PATH="build/tools-install/bin:$PATH"
        exec cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        export PATH="build/tools-install/bin:$PATH"
        exec cmake --build build --parallel