name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
    - uses: hendrikmuhs/ccache-action@v1

    - name: Install Conan
      run: pip install --upgrade conan

    - name: Configure
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --parallel