name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Install
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        set -e;
        pip install -U conan;
        mkdir build;
        cd build;
        conan profile new --detect detect-${{ matrix.compiler.c }};
        conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/conan;
        conan install .. --build=missing --profile detect-${{ matrix.compiler.c }} --settings build_type=${{ matrix.build_type }};

    - name: Build
      env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        set -e;
        cd build;
        conan build ..;

    - name: Install
      run: |
        set -e;
        cd build;
        conan package ..;