name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Install
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        set -e;
        pip install -U conan;
        mkdir build;
        cd build;
        conan profile new --detect detect-${{ matrix.compiler.c }};
        conan profile update settings.compiler.libcxx=libstdc++11 detect-${{ matrix.compiler.c }}
        conan install .. --build=missing -pr detect-${{ matrix.compiler.c }} -s build_type=${{ matrix.build_type }} -e CC=${{ matrix.compiler.c }} -e CXX=${{ matrix.compiler.cxx }}; 

    - name: Build
      env:
        CC: 
        CXX: 
      run: |
        set -e;
        cd build;
        source activate.sh;
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }};
        cmake --build . --parallel;