name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Build dependencies
      run: |
        set -e;
        pip install -U conan;
        mkdir build;
        cd build;
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
        conan install .. --build=missing;

    - name: Configure
      env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        set -e;
        source build/activate.sh;
        cmake -S . -B build/ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_WARNINGS:BOOL=ON

    - name: Build
      run: |
        set -e;
        source build/activate.sh;
        cmake --build build/ --parallel