name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Building for x86_64-pc-linux-gnu (${{ matrix.build_type }}) with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc
            cxx: g++
          - c: clang
            cxx: clang++
        build_type:
          - Release
          - Debug
    defaults:
      run:
        shell: /usr/bin/bash --login -eo pipefail {0}
      env:
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}

    steps:
    - uses: actions/checkout@v2

    - run: pip install --upgrade conan

    - name: cache conan packages
      uses: actions/cache@v2
      with:
        path: ~/.conan2/p
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:conan

    - name: cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.cache/ccache
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:ccache

    - run: conan install -u . --version $(git log -1 --format='%H') -u -b missing -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }}
    - run: conan build . --version $(git log -1 --format='%H')