name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for x86_64-pc-linux-gnu (${{ matrix.build_type }}) with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type:
          - Release
          - Debug

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: pip install --upgrade conan

    - name: Cache Conan Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
          !~/.conan/data/egl/system/**
          !~/.conan/data/glu/system/**
          !~/.conan/data/gtk/system/**
          !~/.conan/data/libudev/system/**
          !~/.conan/data/libopengl/system/**
          !~/.conan/data/vaapi/system/**
          !~/.conan/data/vdpau/system/**
          !~/.conan/data/xorg/system/**
        key: x86_64-pc-linux-gnu_${{ matrix.compiler.c }}_${{ matrix.build_type }}_conan

    - uses: hendrikmuhs/ccache-action@v1

    - name: Configure
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --build build --parallel