name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-10
            cxx: g++-10
          - c: clang-11
            cxx: clang++-11
        build_type:
          - Release
          - Debug

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: pip install --upgrade conan

    - name: Cache Conan Packages
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
          # Do not cache system packages
          !~/.conan/data/*/system 
        key: ${{ runner.os }}_${{ matrix.compiler.c }}_${{ matrix.compiler.cxx }}_${{ matrix.compiler.build_type }}_conan

    - uses: hendrikmuhs/ccache-action@v1

    - name: Cache ccache
      id: cache-ccache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/ccache
        key: ${{ runner.os }}_${{ matrix.compiler.c }}_${{ matrix.compiler.cxx }}_${{ matrix.compiler.build_type }}_ccache


    - name: Configure
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CC: ${{ matrix.compiler.c }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --build build --parallel