name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Building for x86_64-pc-linux-gnu (${{ matrix.build_type }}) with ${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc-11
            cxx: g++-11
          - c: clang-14
            cxx: clang++-14
        build_type:
          - Release
          - Debug
    defaults:
      run:
        shell: bash
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install ${{ matrix.compiler.cc }}
      if: startsWith(matrix.compiler.cc, 'clang')
    - run: exec pip install --upgrade conan

    - name: cache conan packages
      uses: actions/cache@v2
      with:
        path: ~/.conan2/p
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:conan

    - name: cache ccache
      uses: actions/cache@v2
      with:
        path: ~/.cache/ccache
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:ccache

    - run: exec conan profile detect
    - run: exec conan install -u . --version "scm.$GITHUB_SHA" -u -b missing -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
    - run: exec conan build . --version "scm.$GITHUB_SHA"