name: CI
# https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup CMake
      uses: lukka/get-cmake@v3.18.0

    - name: Configure
      shell: cmake -P {0}
      run: |
        if ("${{ matrix.os }}" STREQUAL "windows-latest")
          execute_process(
            COMMAND ${CMAKE_COMMAND} -S . -B build/
            RESULT_VARIABLE result
          )
        else()
          execute_process(
            COMMAND ${CMAKE_COMMAND} -S . -B build/ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            RESULT_VARIABLE result
          )
        endif()
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()

    - name: Build
      shell: cmake -P {0}
      run: |
        if ("${{ matrix.os }}" STREQUAL "windows-latest")
          execute_process(
            COMMAND ${CMAKE_COMMAND} --build build/ --config ${{ matrix.build_type }} --parallel
            RESULT_VARIABLE result
          )
        else()
          execute_process(
            COMMAND ${CMAKE_COMMAND} --build build/ --parallel
            RESULT_VARIABLE result
          )
        endif()
        if (NOT result EQUAL 0)
          message(FATAL_ERROR "Bad exit status")
        endif()