name: Build MinGW-w64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mingw:
    name: Building for ${{ matrix.build_type }} with mingw-w64-${{ matrix.compiler.c }}
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
        matrix:
          compiler:
            - c: gcc
              cxx: g++
          toolchain:
            - /usr/x86_64-w64-mingw32
          target_host: 
            - x86_64-w64-mingw32
          build_type:
            - Release
            - Debug

    steps:
    - uses: actions/checkout@v2
    - uses: hendrikmuhs/ccache-action@v1

    - name: Install build tools
      run: |
        set -e;
        sudo apt-get upgrade;
        sudo apt-get install -y mingw-w64;

    - name: Install Conan
      run: pip install --upgrade conan

    - name: Configure
      env:
        CONAN_SYSREQUIRES_MODE: enabled
        CONAN_CMAKE_FIND_ROOT_PATH: ${{ matrix.toolchain }}
        CONAN_CMAKE_SYSROOT: ${{ matrix.toolchain }}
        CHOST: ${{ matrix.target_host }}
        AR: ${{ matrix.target_host }}-ar
        AS: ${{ matrix.target_host }}-as
        RANLIB: ${{ matrix.target_host }}-ranlib
        CC: ${{ matrix.target_host }}-${{ matrix.compiler.c }}
        CXX: ${{ matrix.target_host }}-${{ matrix.compiler.cxx }}
        STRIP: ${{ matrix.target_host }}-strip
        RC: ${{ matrix.target_host }}-windres
        LDFLAGS: -static-libgcc -static-libstdc++ -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: cmake --build build --parallel