name: Build MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-msys2:
    name: Building for x86_64-w64-mingw32 (${{ matrix.build_type }}) with ${{ matrix.compiler.c }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc
            cxx: g++
          - c: clang
            cxx: clang++
        build_type:
          - Release
          - Debug
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setting up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang

      - uses: actions/checkout@v2

      - name: Install conan
        run: python -m pip install --upgrade conan

      - name: Configure
        env:
          CONAN_BASH_PATH: msys2
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cxx }}
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel