name: Build MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-msys2:
    name: Building for ${{ matrix.build_type }} with ${{ matrix.compiler.c }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: gcc
            cxx: g++
          - c: clang
            cxx: clang++
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v2

      - name: Setting up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang

      - name: Build dependencies
        shell: msys2 {0}
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          set -e;
          python -m pip install -U conan;
          mkdir build;
          cd build;
          conan profile new --detect detect-${{ matrix.compiler.c }};
          conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/conan;
          conan install -pr detect-${{ matrix.compiler.c }} .. --build=missing;

      - name: Configure
        shell: msys2 {0}
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          set -e;
          source build/activate.sh;
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_WARNINGS:BOOL=ON

      - name: Build
        shell: msys2 {0}
        run: |
          set -e;
          source build/activate.sh;
          cmake --build build/ --parallel
