name: Build Win32

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Building for x86_64-pc-windows-msvc (${{ matrix.build_type }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
          - Debug
    steps:
    - uses: actions/checkout@v2
    - run: pip install --upgrade conan
    - run: conan install . --version $(git log -1 --format='%H') -u -b missing -s compiler.cppstd=20 -s build_type=${{ build_type }}
    - run: conan build . --version $(git log -1 --format='%H')