name: Build Win32

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Building for x86_64-pc-windows-msvc (${{ matrix.build_type }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
          - Debug
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - run: exec pip install --upgrade conan
    - run: exec conan profile detect

    - name: cache conan packages
      uses: actions/cache@v2
      with:
        path: ~/.conan2/p
        key: x86_64-linux-gnu:${{ matrix.compiler.c }}:${{ matrix.build_type }}:conan

    - run: exec conan install . --version "scm.$GITHUB_SHA" -u -b missing -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }}
    - run: exec conan build . --version "scm.$GITHUB_SHA" -s compiler.cppstd=20 -s build_type=${{ matrix.build_type }}